client: Finish all opentracing.Spans in test
We've been experiencing flaky tests in client/dial_test.go [1]:

=== RUN   TestDial_Tracing
=== RUN   TestDial_Tracing/unary
=== RUN   TestDial_Tracing/stream
    dial_test.go:355:
                Error Trace:    dial_test.go:355
                Error:          Not equal:
                                expected: "stub"
                                actual  : ""

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -stub
                                +
                Test:           TestDial_Tracing/stream
--- FAIL: TestDial_Tracing (0.02s)
    --- PASS: TestDial_Tracing/unary (0.01s)
    --- FAIL: TestDial_Tracing/stream (0.01s)

In an attempt to fix these flaky tests, ensure Finish() is called on all
instances of opentracing.Span.

[1] https://gitlab.com/gitlab-org/gitaly/-/issues/3402